services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    command: --local-infile=1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_ui
    restart: always
    
    ports:
      - "8080:8080"

volumes:
  mysql_data:
